import Head from 'next/head';
import MainForm from '../src/components/MainForm';
import reports from '../report.json';

export default function Home() {
  return (
    <div className='px-8'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <MainForm reports={reports} />
    </div>
  );
}
